# Generated by Django 6.0.1 on 2026-02-13 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PDFUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=255)),
                ('current_subcategory', models.CharField(default='Genel', help_text="The last detected subcategory (e.g. 'Anemiler'). Used for continuity.", max_length=255)),
                ('incomplete_question_data', models.JSONField(blank=True, help_text='Temporary buffer for questions split across pages', null=True)),
                ('is_processing', models.BooleanField(default=False, help_text='True if background task is running')),
                ('total_pages', models.IntegerField(default=0)),
                ('last_processed_page', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.category')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(blank=True, help_text='The number from the original book', null=True)),
                ('subcategory', models.CharField(blank=True, default='Genel', max_length=255, null=True)),
                ('text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_option', models.CharField(max_length=1)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('page_number', models.IntegerField(help_text='The page number in the PDF')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='content.test'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('test', 'name')},
        ),
    ]
