# Generated by Django 6.0.1 on 2026-02-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_systemconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemConfig',
        ),
    ]
