# Generated by Django 6.0.1 on 2026-03-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_delete_systemconfig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pdfupload",
            name="current_subcategory",
        ),
        migrations.RemoveField(
            model_name="pdfupload",
            name="incomplete_question_data",
        ),
        migrations.AddField(
            model_name="pdfupload",
            name="parser_state",
            field=models.JSONField(blank=True, default=dict, help_text="Stores parsing state between pages: buffer, subcategory, pending_explanations"),
        ),
    ]
