# Generated by Gemini CLI - Squashed Initial Migration

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0005_remove_pdfupload_current_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCategoryProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_count', models.IntegerField(default=0)),
                ('total_answered', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser')),
            ],
            options={
                'unique_together': {('user', 'category')},
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField()),
                ('is_active', models.BooleanField(default=True, help_text='Used to filter current quiz progress')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='bot.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='PollMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('chat_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser')),
            ],
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['user', 'is_correct'], name='bot_userans_user_id_49f3ce_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['user', 'is_active'], name='bot_userans_user_id_25dedd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('user', 'question')},
        ),
    ]
